[project]
name = "ddb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "datetime>=5.5",
    "dotenv>=0.9.9",
    "duckdb>=1.2.0",
    "requests>=2.32.3",
]
